### ISSUE TITLE
Problem with LZ4F_cctx and LZ4G_dctx

### ISSUE THREAD

**Issue by rvbarreto** [chatnoir-eu/chatnoir-resiliparse#1]
I'm having this error both when trying to install from pip and from this repo:

fastwarc/warc.cpp:1189:3: error: ‘LZ4F_cctx’ does not name a type; did you mean ‘LZ4F_cctx_s’?
   LZ4F_cctx *cctx;
   ^~~~~~~~~
   LZ4F_cctx_s
fastwarc/warc.cpp:1190:3: error: ‘LZ4F_dctx’ does not name a type; did you mean ‘LZ4F_dctx_s’?
   LZ4F_dctx *dctx;
   ^~~~~~~~~
   LZ4F_dctx_s
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by phoerious** [comment]
Hi, sorry for the late response.
The error you see is because your LZ4 version is too old. Use the pre-compiled binaries instead.
