### ISSUE TITLE
Type annotations

### ISSUE THREAD

**Issue by heinrichreimer** [chatnoir-eu/chatnoir-resiliparse#30]
It would be incredibly useful for this library to include type annotations and to declare itself as a [PEP 561 compliant stub package](https://mypy.readthedocs.io/en/stable/installed_packages.html#installed-packages).

**Comment by phoerious** [comment]
All the native components come with text signatures, which do the same thing. Unfortunately, there is no automatic way to maintain stub packages with Cython at the moment. I think Cython 3.0.0 supports type annotations now, but it's absolutely unclear from the documentation what that actually means for our use case.

**Comment by phoerious** [comment]
At least for FastWARC, a manual stub file has been added and I've tagged and submitted a new release for it. Hence, I will close this now.

/cc @habibutsu @jonded94

**Comment by janheinrichmerker** [comment]
Very nice, thank you!
