### ISSUE TITLE
Nested Span 

### ISSUE THREAD

**Issue by timmytwoteeth** [chatnoir-eu/chatnoir-resiliparse#42]
Hello,

I was wondering if you had any input on what would be the best way to traverse and remove the contents of a nested span?

Nested span to traverse:
```
<span normalizedcite="<span class="citation no-link">98 T.C. 141</span>">98 T.C. 141</span>
```
Span to remove or replace:
```
"<span class="citation no-link">98 T.C. 141</span>"
```
Using query selector all does not seem to get the `.normalizedcite` class.

Thank you

**Comment by wumpus** [comment]
Is that valid html? Shouldn't it be:

```
<span class="normalizedcite"><span class="citation no-link">98 T.C. 141</span>98 T.C. 141</span>
```

**Comment by phoerious** [comment]
Yeah, this is definitely strange nesting.

**Comment by timmytwoteeth** [comment]
> Is that valid html? Shouldn't it be:
> 
> ```
> <span class="normalizedcite"><span class="citation no-link">98 T.C. 141</span>98 T.C. 141</span>
> ```

Unfortunately, these types of nested spans are part of the HTML for numerous documents in this corpus and are all formatted as such: `<span normalizedcite="<span class="citation no-link">102 T.C. 790</span>">102 T.C. 790</span>`

> Yeah, this is definitely strange nesting.

I definitely agree the nesting is strange. This is an edge case I am unsure of how to resolve.

**Comment by wumpus** [comment]
If it's non-standard HTML I would try to pre-process it into standard html... if it's just this one case it's not too hard.

**Comment by timmytwoteeth** [comment]
> If it's non-standard HTML I would try to pre-process it into standard html... if it's just this one case it's not too hard.

Unfortunately, this is not the only case. 

I am currently applying pre-processing to handle some edge cases but I did not know if it was possible to directly handle these nested spans. I appreciate the input and will work on correctly regexing for pre-processing before traversal.
